### ISSUE TITLE
Center Form Elements

### ISSUE THREAD

**Issue by philsinatra** [jel99/idm231#3]
Your form container `#pokeInfo` is centered on the page already:

<img width="566" alt="screen shot 2018-02-01 at 12 02 10 pm" src="https://user-images.githubusercontent.com/1465808/35691947-e4ab3728-0747-11e8-869c-3d2725027125.png">

The issue is your `input` elements are not filling the entire width of the container.  You have two declarations in you CSS that are causing this. These declarations can be found in the follow code blocks:

```css
input[type=text], input[type=date] {
  width: 18.75rem;
  margin: 0.3125rem auto;
}
```

```css
input[type=text], input[type=date] {
  font-size: 1rem;
  font-family: 'pokemon_gbregular';
  text-transform: uppercase;

  border-radius: 0.125rem;
  padding: 0.5rem;
  width: 100% /* on desktop 18.75rem */;
  max-width: 18.75rem;
  height: 3.125rem;
  line-height: 1rem;
  margin: 0.3125rem auto;

  background: white;
  border: 1px solid white;
  box-shadow: 0 1px 0 1px black,
              inset 0 1px 0 1px black,
              0 0 0 1px black,
              inset 0 0 0 1px black;
}
```
